import 'tempo_change.dart';

class Song {
  final String id;
  final String title;
  final String composer;
  final String keySignature;
  final String timeSignature;
  final int bpm;
  final String difficulty;
  final LessonType lessonType;
  final String? chordName;
  final List<int>? chordIntervals;
  final bool arpeggio;
  final List<TempoChange> tempoMap;

  const Song({
    required this.id,
    required this.title,
    required this.composer,
    required this.keySignature,
    required this.timeSignature,
    required this.bpm,
    required this.difficulty,
    this.lessonType = LessonType.song,
    this.chordName,
    this.chordIntervals,
    this.arpeggio = false,
    this.tempoMap = const [],
  });
}

enum LessonType { song, chord }

class SongLibrary {
  static const List<Song> songs = [
    Song(
      id: 's1',
      title: 'Moonlight Prelude',
      composer: 'Trad.',
      keySignature: 'C Major',
      timeSignature: '4/4',
      bpm: 72,
      difficulty: 'Beginner',
    ),
    Song(
      id: 's2',
      title: 'River Waltz',
      composer: 'Trad.',
      keySignature: 'G Major',
      timeSignature: '3/4',
      bpm: 96,
      difficulty: 'Intermediate',
    ),
    Song(
      id: 's3',
      title: 'Night Etude',
      composer: 'Trad.',
      keySignature: 'A minor',
      timeSignature: '4/4',
      bpm: 108,
      difficulty: 'Advanced',
    ),
    Song(
      id: 'c1',
      title: 'Fmaj7 Chord',
      composer: 'Chord Practice',
      keySignature: 'F',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Fmaj7',
      chordIntervals: [0, 4, 7, 11],
      arpeggio: false,
    ),
    Song(
      id: 'c2',
      title: 'Fmaj7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'F',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Fmaj7',
      chordIntervals: [0, 4, 7, 11],
      arpeggio: true,
    ),
    Song(
      id: 'c3',
      title: 'Fm6 Chord',
      composer: 'Chord Practice',
      keySignature: 'F',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Fm6',
      chordIntervals: [0, 3, 7, 9],
      arpeggio: false,
    ),
    Song(
      id: 'c4',
      title: 'Fm6 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'F',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Fm6',
      chordIntervals: [0, 3, 7, 9],
      arpeggio: true,
    ),
    Song(
      id: 'c5',
      title: 'Em7 Chord',
      composer: 'Chord Practice',
      keySignature: 'E',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Em7',
      chordIntervals: [0, 3, 7, 10],
      arpeggio: false,
    ),
    Song(
      id: 'c6',
      title: 'Em7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'E',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Em7',
      chordIntervals: [0, 3, 7, 10],
      arpeggio: true,
    ),
    Song(
      id: 'c7',
      title: 'Ebdim7 Chord',
      composer: 'Chord Practice',
      keySignature: 'Eb',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Ebdim7',
      chordIntervals: [0, 3, 6, 9],
      arpeggio: false,
    ),
    Song(
      id: 'c8',
      title: 'Ebdim7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'Eb',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Ebdim7',
      chordIntervals: [0, 3, 6, 9],
      arpeggio: true,
    ),
    Song(
      id: 'c9',
      title: 'Dm7 Chord',
      composer: 'Chord Practice',
      keySignature: 'D',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Dm7',
      chordIntervals: [0, 3, 7, 10],
      arpeggio: false,
    ),
    Song(
      id: 'c10',
      title: 'Dm7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'D',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Dm7',
      chordIntervals: [0, 3, 7, 10],
      arpeggio: true,
    ),
    Song(
      id: 'c11',
      title: 'G7 Chord',
      composer: 'Chord Practice',
      keySignature: 'G',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'G7',
      chordIntervals: [0, 4, 7, 10],
      arpeggio: false,
    ),
    Song(
      id: 'c12',
      title: 'G7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'G',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'G7',
      chordIntervals: [0, 4, 7, 10],
      arpeggio: true,
    ),
    Song(
      id: 'c13',
      title: 'Cmaj7 Chord',
      composer: 'Chord Practice',
      keySignature: 'C',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Cmaj7',
      chordIntervals: [0, 4, 7, 11],
      arpeggio: false,
    ),
    Song(
      id: 'c14',
      title: 'Cmaj7 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'C',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'Cmaj7',
      chordIntervals: [0, 4, 7, 11],
      arpeggio: true,
    ),
    Song(
      id: 'c15',
      title: 'C6 Chord',
      composer: 'Chord Practice',
      keySignature: 'C',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'C6',
      chordIntervals: [0, 4, 7, 9],
      arpeggio: false,
    ),
    Song(
      id: 'c16',
      title: 'C6 Arpeggio',
      composer: 'Chord Practice',
      keySignature: 'C',
      timeSignature: '4/4',
      bpm: 50,
      difficulty: 'Beginner',
      lessonType: LessonType.chord,
      chordName: 'C6',
      chordIntervals: [0, 4, 7, 9],
      arpeggio: true,
    ),
  ];
}
